---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: copy from master to client
      copy: src=/var/lib/awx/projects/_10__copyyml/file.txt dest=/tmp/filecopy.txt owner=root group=root mode=0777 
